version: '3.9'

services:

  fast_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_server
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - DATABASE_URL={DATABASE_URL}
      - DATABASE_NAME={DATABASE_NAME}
      - DATABASE_COLLECTION={DATABASE_COLLECTION}
      - PORT={PORT}
    ports:
      - 8000:{PORT}

  mongo:
    image: mongo
    container_name: mongo_database
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - .docker/mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro
